### ISSUE TITLE
Remove unrelated dependencies

### ISSUE THREAD

**Issue by the-x-at** [EricArcher/rfPermute#10]
Inclusion of the convenience package `swfscMisc`, also written by @EricArcher, drags in an incredible amount of overhead. This package depends on R package `sf`, which in turn depends on geospatial libraries `gdal` and `geos` (to be installed on the operating system (OS) level), both of them are most likely not used in the context of `rfPermute`. 

Building from source on an older Mac using Fink was rather complicated. First surprise was a dependency on R package `s2` (via package `sf`), which took some time to compile. After that, package `sf` did not compile successfully as during configuration phase `gdal` and `geos` libraries were found to be missing on the OS level. These two libraries dragged in another 30+ dependencies and overall compilation time was three (3) _hours_.

**Comment by EricArcher** [comment]
There are 2 functions in 'rfPermute' that rely on 2 functions in 'swfscMisc'. Although I could copy them into 'rfPermute', I do not want to maintain them in two separate places. They exist in 'swfscMisc' because I use them by themselves and in other packages as well. Thus, it is not possible to remove all dependencies of 'rfPermute' on 'swfscMisc'.

**Comment by the-x-at** [comment]
This sounds however encouraging. The solution would be to split `swfscMisc` into more independent modules that have a clear list of dependencies and well-defined tasks instead of mixing many things together. Assuming the two functions are only for plotting, that way e.g. a `plottingMisc` R-package would be included by `swfscMisc` and by `rfPermute` and the latter would be free of most other not-needed dependencies, and of `swfscMisc` itself.

**Comment by EricArcher** [comment]
Thanks for that suggestion. I will consider it when I do my next update to 'swfscMisc'
