### ISSUE TITLE
bug fix in clean.rf.data

### ISSUE THREAD

**Issue by sorhawell** [EricArcher/rfPermute#2]
#bug fix suggestion

    #testing
    install.packages("rfPermute")
    library(rfPermute)
    Data = data.frame(replicate(5,rnorm(100)))
    Data[,1] = 7     #constant column "X1" should be removed
    Data[2,2] = NA  #missing value in row 2 should be removed
    head(Data)
    Data = data.frame(X,y)
    out = clean.rf.data(1:4, 5, Data)
    head(out) #column "X1" is still there

    #fix
    #overwrite function in global environment
    clean.rf.data = function (x, y, data, max.levels = 30)
    {
      x <- setdiff(x, y)
      sub.df <- data[, c(y, x)]
      sub.df <- sub.df[complete.cases(sub.df), , drop = TRUE]
      delete.pred <- character(0)
      for (pred in x) {
        pred.vec <- sub.df[[pred]]
        if (length(unique(pred.vec)) <= 1) #change this line from, ==0
          delete.pred <- c(delete.pred, pred)
        if (is.factor(pred.vec) & (nlevels(pred.vec) > max.levels))
          delete.pred <- c(delete.pred, pred)
      }
      delete.pred <- unique(delete.pred)
      if (length(delete.pred) > 0)
        x <- setdiff(x, delete.pred)
      if (is.factor(sub.df[[y]]) & nlevels(sub.df[[y]][, drop = TRUE]) <
          2)
        return(NULL)
      sub.df[, c(y, x)]
    }

    #checking
    out2 = clean.rf.data(1:4, 5, Data)
    head(out2) #column "X1" is now gone

**Comment by EricArcher** [comment]
Fixed.
