### ISSUE TITLE
How to understand the P-values from rfPermute？

### ISSUE THREAD

**Issue by ghost** [EricArcher/rfPermute#6]
Hi Eric,

I am little confused about p-value from the following command: 
`rp <- rfPermute(factor(am) ~ ., mtcars, nrep = 100, num.cores = 1)
`
How to understand the P-values from rfPermute? Thanks. 
![image](https://user-images.githubusercontent.com/80598863/111090148-121aa980-8505-11eb-90da-4ad65c34c763.png)

David

**Comment by EricArcher** [comment]
Can you be a bit more specific in your question? Exactly what are you confused about with respect to the p-values? What do you understand and what don't you understand?
