### ISSUE TITLE
Hypothesis Testing/CI on Variable Importance in random forests

### ISSUE THREAD

**Issue by pachard** [EricArcher/rfPermute#7]
Dear Eric,

I would like to compare variable importance between variables using random forests. To do so, I wanted to build CI around the estimated mean decrease accuracy and see if they would overlap between variables.

I was wondering if the approach below is valid: taking the SE estimated by rfPermute and construct CI using the forumla ±1.96*SЕ 

results <- rfPermute(Y ~ some Xs, data = data, na.action = na.omit)
 importance <- as.matrix(results$importanceSD[,3])
 importance1 <- as.matrix(importance(results, type = 1, scale= FALSE))
 blabla <- importance1 - 1.96importance
 blabla1 <- importance1 + 1.96importance
 output <- cbind(importance1, importance, blabla, blabla1)

If I am willing to make the assumption that the distribution of mean decrease accuracy among OOB is normally distributed, is this approach valid?
Thanks in advance, 
Best,
Pascal

**Comment by EricArcher** [comment]
Pascal,
I see nothing wrong with doing that to compute an importance CI. Pretty straightforward.

Cheers,
Eric
