### ISSUE TITLE
Add option to feed trained randomForest model into rfPermute()

### ISSUE THREAD

**Issue by Eznir34** [EricArcher/rfPermute#8]
In my opinion, it would be a great feature to have the opportunity to feed rfPermute() an already trained randomForest model so that it uses the feature importance scores from that model instead of training a new forest. This allows for a more coherent analysis throughout the research application.

**Comment by EricArcher** [comment]
Could you clarify your request a bit? Are you suggesting adding the ability to estimate significance of variable importance from an already trained randomForest model?
How would this add for a more coherent analysis if a user can run the same model in rfPermute and create the estimates simulataneously? Isn't that the most coherent?
