### ISSUE TITLE
There is NA in %IncMSE.pval.

### ISSUE THREAD

**Issue by WeiFurong** [EricArcher/rfPermute#9]
Hi,
    There are many NA in the %IncMSE.pval. If I change the number of the seed or ntree, NA will increase or decrease.  
%IncMSE | %IncMSE.pval | IncNodePurity | IncNodePurity.pval
4.9089802 | 0.02970297 | 1262.8835 | 0.00990099
3.4689366 | 0.12871287 | 952.313 | 0.13861386
2.3781035 | NA | 491.9594 | 0.6039604
2.3378941 | NA | 953.8426 | 0.07920792
2.1870641 | NA | 675.8061 | 0.20792079
1.7889514 | NA | 479.9947 | 0.4950495
1.7102849 | 0.18811881 | 451.7091 | 0.65346535
1.6046331 | NA | 656.7826 | 0.30693069
1.0245411 | NA | 784.2426 | 0.17821782
0.463957 | NA | 479.3047 | 0.51485149
-0.7036787 | 0.5049505 | 441.574 | 0.55445545
-1.3277221 | NA | 431.3065 | 0.56435644
-1.9111734 | NA | 413.4493 | 0.75247525
-2.2478055 | NA | 210.2557 | 1
-2.9267568 | NA | 241.034 | 0.96039604

Code:
set.seed(123)
otu_rfP<- rfPermute(SR ~ ., data = otu, ntree=500,
                    na.action = na.omit,nrep = 999,num.cores = 1)

**Comment by EricArcher** [comment]
Would you send me an .rdata or .rds file that contains the `otu` data.frame so I can try to reproduce and examine this issue?

**Comment by WeiFurong** [comment]
Dear Eric,
The otu data.frame is delivered as an attachment.Thanks very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricArcher/rfPermute"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 凌晨0:50
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [EricArcher/rfPermute] There is NA in %IncMSE.pval. (Issue #9)





 
Would you send me an .rdata or .rds file that contains the otu data.frame so I can try to reproduce and examine this issue?

**Comment by EricArcher** [comment]
I do not see an attachment. Feel free to send it to me via email (eric.archer@noaa.gov)

**Comment by EricArcher** [comment]
This behavior was occurring because some permutations generate NaNs for %IncMSE. To fix this, I had to update the `pVal()` function in the `swfscMisc` package that computes the p-values. You will need to update this package from my GitHub repository ([ericarcher/swfscMisc](https://github.com/EricArcher/swfscMisc)) to implement this change.

**Comment by WeiFurong** [comment]
Dear Eric,
As your suggestion, I installed the latest swfscMisc package and then rerun the same code as before. Fortunately, it did work. There was no more NA in the %IncMSE.pval. Thank you again very much.
